---
image: docker:stable

variables:
  DOCKER_REGISTRY_IMAGE: "${CI_REGISTRY_IMAGE}"
  DOCKER_REGISTRY_IMAGE_TAG: latest

services:
  - docker:dind

before_script:
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}

stages:
  - build
  - test

build_image:
  stage: build
  script:
    - docker build -t ${DOCKER_REGISTRY_IMAGE}:${CI_COMMIT_SHA} .
    #- docker push ${DOCKER_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
    - docker tag ${DOCKER_REGISTRY_IMAGE}:${CI_COMMIT_SHA} ${DOCKER_REGISTRY_IMAGE}:${DOCKER_REGISTRY_IMAGE_TAG}
    - docker push ${DOCKER_REGISTRY_IMAGE}:${DOCKER_REGISTRY_IMAGE_TAG}
